version: '3.5'

services:
  minecraft-test:
    container_name: minecraft-test
    image: itzg/minecraft-server
    env_file: .env
    tty: true
    stdin_open: true
    entrypoint: ['sh', '-c', 'crond && /opt/mc/start_mc.sh']
    # entrypoint: tail -f /dev/null
    volumes:
      - ./volumes/minecraft/minecraft-test:/data
      - ./volumes/minecraft/forge-mods:/mods
      - ./volumes/minecraft/forge-mods:/data/config/bluemap/resourcepacks #Bluemap loads mods as resourcepacks for gfx
      # Backup Mounts
      - ./scripts/mc/:/opt/mc:ro
      - ./scripts/mc/crontabs:/etc/periodic
      - ./volumes/minecraft/backups/minecraft-test/live:/mc/live
      - ./volumes/minecraft/backups/minecraft-test/archived:/mc/archived
      - /dev/shm/minecraft-test:/mc/volatile
    environment:
      VERSION: '1.16.4'
      MEMORY: '4G'
      TYPE: 'FORGE'
      MOTD: "Testing, don't join"
    ports:
      - '1234:25565'
