version: "3.5"

services:
  plex:
    container_name: plex
    image: linuxserver/plex
    network_mode: host
    environment:
      - VERSION=docker
    volumes:
      - ./volumes/plex:/config
      - /media/nfg/Media/Video/Movies:/movies
    restart: unless-stopped
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    restart: unless-stopped
    env_file: .env
    network_mode: host
    volumes:
      - ./volumes/media/deluge:/config
      - /media/nfg/Media/Video/!incoming:/downloads


  radarr:
    container_name: radarr
    image: linuxserver/radarr
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./volumes/media/radarr:/config
      - /media/nfg/Media/Video/Movies:/movies
      - /media/nfg/Media/Video/!incoming:/downloads
    ports:
      - 7878:7878

      