version: '3.5'

services:
  minecraft-router:
    container_name: minecraft-router
    image: itzg/mc-router
    restart: unless-stopped
    ports:
      - 25565:25565
    command: --mapping=dc-ed7b6af9d67e.nfgarmy.com.=minecraft-prim:25565,dc-aa2ae8691955.nfgarmy.com.=minecraft-bedrock-converted:25565

  minecraft-rcon:
    container_name: minecraft-rcon
    image: itzg/rcon
    restart: unless-stopped
    env_file: .env
    ports:
      - '4326:4326'
      - '4327:4327'
    volumes:
      - './volumes/minecraft/rcon:/opt/rcon-web-admin/db'

  minecraft-prim:
    container_name: minecraft-prim
    image: itzg/minecraft-server
    restart: unless-stopped
    env_file: .env
    tty: true
    stdin_open: true
    deploy:
      resources:
        limits:
          cpus: '4'
    entrypoint: ['sh', '-c', 'crond && /opt/mc/start_mc.sh']
    volumes:
      - ./volumes/minecraft/minecraft-prim:/data
      - ./volumes/minecraft/forge-mods:/mods
      - ./volumes/minecraft/forge-mods:/data/config/bluemap/resourcepacks #Bluemap loads mods as resourcepacks for gfx

      # Runtime Scripts/Crontabs
      - ./scripts/mc/:/opt/mc:ro
      - ./scripts/mc/crontabs:/etc/periodic:ro
      # Backup Mounts
      - ./volumes/minecraft/backups/minecraft-prim/live:/mc/live
      - ./volumes/minecraft/backups/minecraft-prim/archived:/mc/archived
      - /dev/shm/minecraft-prim:/mc/volatile
    environment:
      VERSION: '1.16.4'
      MEMORY: '8G'
      TYPE: 'FORGE'
      # Override server.properties
      LEVEL_TYPE: 'biomesoplenty'
      MOTD: "\\u00A76NFG\\u00A7dArmy\\u00A76 Primitive\\u00A7r - \\u00A7burl.nfgarmy.com/discord\\u00A7r\\nVanilla MineCraft with a \\u00A7alittle bit extra!"

  # minecraft-bedrock-converted:
  #   container_name: minecraft-bedrock-converted
  #   image: itzg/minecraft-server
  #   restart: unless-stopped
  #   env_file: .env
  #   tty: true
  #   stdin_open: true
  #   volumes:
  #     - ./volumes/minecraft/minecraft-bedrock-converted:/data
  #     - ./volumes/minecraft/forge-mods:/mods
  #   environment:
  #     VERSION: '1.16.4'
  #     MEMORY: '4G'
  #     TYPE: 'FORGE'
  #     # Override server.properties
  #     MOTD: "\\u00A76NFG\\u00A7dArmy\\u00A76 Bedrock (Converted)\\u00A7r - \\u00A7burl.nfgarmy.com/discord \\u00A7rRemember the old xbox server?"

  # minecraft-bedrock:
  #   container_name: minecraft-bedrock
  #   image: itzg/minecraft-bedrock-server
  #   restart: unless-stopped
  #   env_file: .env
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     EULA: "true"
  #     ALLOW_CHEATS: 'true'
  #     GAMEMODE: creative
  #     DIFFICULTY: normal
  #     VIEW_DISTANCE: 24
  #     PLAYER_IDLE_TIMEOUT: 10
  #     SERVER_NAME: "NFGArmy Bedrock Server!"
  #     MAX_PLAYERS: 40
  #   ports:
  #     - 19132:19132/udp
  #   volumes:
  #     - ./volumes/minecraft/bedrock:/data
