version: '3.5'

services:
  home-assistant:
    container_name: home-assistant
    image: homeassistant/home-assistant:stable
    restart: unless-stopped
    env_file: .env
    ports:
      - '8123:8123'
    volumes:
      - ./volumes/ha:/config
    devices:
      - /dev/serial/by-id/usb-0658_0200-if00:/zwaveusbstick

  motioneye:
    container_name: motioneye
    image: ccrisan/motioneye:master-amd64
    restart: unless-stopped
    env_file: .env
    ports:
      - '8766:8081'
      - '8765:8765'
    volumes:
      - ./volumes/motioneye/etc:/etc/motioneye
      - ./volumes/motioneye/var_lib:/var/lib/motioneye

  # node-red:
  #   container_name: node-red
  #   image: nodered/node-red:latest
  #   restart: unless-stopped
  #   env_file: .env
  #   ports:
  #     - "1880:1880"
  #   volumes:
  #     - ./volumes/node-red:/data
