version: '3.5'

services:
  mariadb:
    container_name: mariadb
    image: linuxserver/mariadb
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./volumes/mariadb:/config
    ports:
      - 3306:3306

  # phpmyadmin:
  #   container_name: phpmyadmin
  #   image: phpmyadmin/phpmyadmin
  #   env_file: .env
  #   ports:
  #     - 8080:80
  #   external_links:
  #     - mariadb:db

  letsencrypt:
    container_name: letsencrypt
    image: linuxserver/letsencrypt
    restart: unless-stopped
    env_file: .env
    cap_add:
      - NET_ADMIN
    environment:
      # - STAGING=true
      - URL=${URL_NFGARMY}
      - SUBDOMAINS=wildcard
      - VALIDATION=dns
      - DNSPLUGIN=cloudflare
      ########
      # - URL=${URL_DUCKDNS}
      # - VALIDATION=duckdns
      # - DUCKDNSTOKEN=${TOKEN_DUCKDNS}
    volumes:
      - ./volumes/letsencrypt:/config
      - ./volumes/minecraft/java-primitive/bluemap/web:/tmp/bluemap/play
      - ./volumes/minecraft/java-bedrockConverted/bluemap/web:/tmp/bluemap/play2
    ports:
      - 80:80
      - 443:443
