version: '3.5'

services:
  db-backup-mariadb:
    container_name: db-backup-mariadb
    image: tiredofit/db-backup
    restart: unless-stopped
    external_links:
      - mariadb
    env_file:
      - .env/.env
      - .env/.env-dbbu-mariadb
    volumes:
      - ../volumes/__BACKUPS/mariadb/:/backup
      - ../volumes/__BACKUPS/post-script.sh:/assets/custom-scripts/post-script.sh
