version: '3.7'

services:
  vrising:
    image: scottyhardy/docker-wine
    container_name: vrising
    restart: unless-stopped
    stdin_open: true
    tty: true
    shm_size: 512mb
    hostname: ${HOST}
    command: /app/start_server
    environment:
      - USER_UID=1000
      - USE_XVFB=yes
      - FORCED_OWNERSHIP=yes
      - DISPLAY=:95
      - XVFB_SERVER=:95
      - XVFB_SCREEN=0
      - XVFB_RESOLUTION=1024x768x16
    ports:
      - '9876:9876/udp'
      - '9877:9877/udp'
      - '47584:47584/udp'
      - '47584:47584/tcp'
    networks:
      - rcon_vlan
    volumes:
      - ../volumes/wine:/home/wineuser/
      - ../volumes/vrising/save-data:/save-data
      - ../volumes/vrising/game:/game
      - ../volumes/vrising/app:/app
      - ${HOME}/.Xauthority:/root/.Xauthority
      # - /tmp/.X11-unix:/tmp/.X11-unix:ro

networks:
  rcon_vlan:
    external: true
