version: '3.7'

services:
  minidlna:
    image: geekduck/minidlna
    container_name: minidlna
    restart: unless-stopped
    network_mode: host
    volumes:
      - /media/nfg/StoreInactive/Media/Video/Movies:/opt/Videos/Movies
      - /media/nfg/StoreInactive/Media/Video/TV Shows:/opt/Videos/TV
      - /media/nfg/StoreInactive/Media/Music:/opt/Music
      - /media/nfg/StoreInactive/Media/Video/_Pr0n:/opt/Videos/!Porn
        # - /media/nfg/StoreInactive/Media/:/opt/Pictures
      - ../volumes/minidlna/minidlna.conf:/etc/minidlna.conf
      - minidlna_cache:/var/cache/minidlna

volumes:
  minidlna_cache:
