services:
  minidlna-pt:
    image: geekduck/minidlna
    container_name: minidlna-pt
    restart: unless-stopped
    network_mode: host
    volumes:
      - /media/nfg/StoreInactive/Media/Video/_Pr0n:/opt/Videos/
      - ../volumes/minidlna/minidlna-pt.conf:/etc/minidlna.conf
      - minidlna_cache-pt:/var/cache/minidlna

volumes:
  minidlna_cache-pt:
