version: '3.7'

services:
  project-zomboid:
    image: afey/zomboid
    container_name: zomboid
    restart: unless-stopped
    env_file: 
      - .env/.env
      - .env/.env-pz
    ports:
      - '8766:8766/udp'
      - '8767:8767/udp'
      - '16261:16261/udp'
      - '16262-16272:16262-16272'
      - '27015:27015'
    volumes:
      - ../volumes/project-zomboid:/server-data
      - pz-server-files:/server-files

volumes:
  pz-server-files:
