{
 "title": "Codex's Linux/Docker Dashboard",
 "description": "A Grafana dashboard for displaying Linux System and Docker Stats via Telegraf",
 "tags": [
  "telegraf",
  "influxdb2",
  "fluxquery"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "InfluxTelegrafDataSource", "label": "InfluxDB/Telegraf Data Source", "query": "influxdb" },
   {
    "name": "baseStyle",
    "label": "Base Style for Components/Display",
    "query": "color: rgb(243, 124, 30); text-shadow: 0px 0px 4px rgb(243, 124, 30);"
   },
   {
    "name": "labelStyle",
    "label": "Label Style for Components/Display",
    "query": "color: rgb(200, 200, 200);  text-shadow: 0px 0px 4px rgba(255, 255, 255, 100);"
   },
   {
    "name": "valueStyle",
    "label": "Value Style for Components/Display",
    "query": "color: #05a8ff; text-shadow: 0px 0px 4px #05a8ff;"
   },
   {
    "name": "valueStyle2",
    "label": "Value Style for Components/Display",
    "query": "color: #0d7cb8; text-shadow: 0px 0px 4px #0d7cb8;"
   },
   {
    "name": "i______________",
    "label": "DO NOT EDIT VARIABLES BELOW THIS"
   },
   {
    "name": "host",
    "label": "Monitor Host",
    "query": "import \"influxdata/influxdb/v1\"\r\n\r\nv1.tagValues(\r\n  bucket: v.defaultBucket,\r\n  tag: \"host\",\r\n  predicate: (r) => true\r\n)"
   },
   {
    "name": "cpucores",
    "label": "Number of CPU Cores for $host",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"system\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"n_cpus\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\r\n  |> yield(name: \"mean\")"
   },
   {
    "name": "memTotal",
    "label": "Total Memory for $host",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"total\" and r.host == \"${host}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n    _time: r._time, _value: r._value / 1000 / 1000 / 1024\r\n  }))\r\n  |> yield(name: \"last\")"
   },
   {
    "name": "numDrives",
    "label": "Number of Drives for $host",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r[\"_measurement\"] == \"disk\" and\r\n      r[\"_field\"] == \"total\" and\r\n      r.host =~ /^${host}$/\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> last()\r\n  |> drop(columns: [\"path\", \"device\"])\r\n  |> map(fn: (r) => ({\r\n      r with _field: \"Count\", _value: r._value, _time: r._time\r\n  }))\r\n  |> count()\r\n  |> yield(name: \"count\")\r\n"
   },
   {
    "name": "numDockerTotal",
    "label": "Number of Docker Containers for $host",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"host\"] == \"${host}\" and\r\n    r[\"_measurement\"] == \"docker\" and\r\n    r[\"_field\"] == \"n_containers\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
   },
   {
    "name": "numDockerRunning",
    "label": "Number of Docker Containers Running on $host",
    "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"host\"] == \"${host}\" and\r\n    r[\"_measurement\"] == \"docker\" and\r\n    r[\"_field\"] == \"n_containers_running\"\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
   }
  ]
 },
 "panels": [
  {
   "title": "README",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 21, "w": 14, "x": 0, "y": 1 },
     "options": {
      "content": "# Welcome!\n\nThis is a Dashboard designed for Linux hosts with Docker containers.\n\n    There is minimal support for Windows, there might be an alternative Dashboard for that later!\n\n## Prerequisites:\n\n* Telegraf\n    * TODO: Supply a full `telegraf.conf` per platform\n* InfluxDB2\n    * This Dashboard utilizes Flux Language for the query syntax, bringing this Dashboard up to current practices with InfluxDB/Flux\n* Grafana 8\n\n## Configuration\n\nBe sure to check out the `Variables` section to ensure you're accessing the right InfluxDBv2 Bucket.\n\n### Current Variables:\n  * InfluxTelegrafDataSource: \"${InfluxTelegrafDataSource}\"\n  * <span style=\"$baseStyle;\">baseStyle</span>\n  * <span style=\"$labelStyle;\">labelStyle</span>\n  * <span style=\"$valueStyle;\">valueStyle</span>\n  * <span style=\"$valueStyle2;\">valueStyle2</span>\n\n        Be sure to not modify any queries, as they are used for both display/informative as well as for calculations!\n\n  Once you've tweaked these variables to your liking, you can remove this entire row!\n\n  Enjoy!"
     }
    }
   ]
  },
  { "title": "[$host] Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }, "repeat": "host" },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"system\" and\r\n    r[\"_field\"] == \"uptime\" and \r\n    r[\"host\"] =~ /^${host}$/\r\n  )\r\n  |> aggregateWindow(every: 1s, fn: last, createEmpty: false)\r\n  |> last()\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"cpu\" and\r\n    r[\"_field\"] == \"usage_idle\" and \r\n    r[\"cpu\"] == \"cpu-total\" and\r\n    r[\"host\"] =~ /^${host}$/\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * -1.0 + 100.0 }))\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"Total\" }))\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"mem\" and\r\n    r._field == \"used\" and\r\n    r.host =~ /^$host$/\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> last()\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Used\" }))\r\n  |> yield(name: \"last\")"
    },
    {
     "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"mem\" and\r\n    r._field == \"total\" and\r\n    r.host =~ /^$host$/\r\n  )\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Total\" }))\r\n  |> yield(name: \"total\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 5, "x": 6, "y": 2 },
   "options": {
    "content": "<span style=\"font-size: 75%\">\r\n\r\n    <div style=\"text-align: right;\">\r\n    <span style=\"$labelStyle; padding-right: 5px;\">viewing</span>\r\n    <span style=\"font-size: 200%; margin: 0;\">\r\n        <span style=\"$baseStyle\">$host</span>\r\n    </span>\r\n    </div>\r\n\r\n    <span style=\"display: inline-block; margin: 0; width: 75px; text-align: right; padding-right: 4px; $labelStyle\">Mem Total: </span><span style=\"font-size: 150%; $valueStyle\">${memTotal}GB</span><br />\r\n    <span style=\"display: inline-block; margin: 0; width: 75px; text-align: right; padding-right: 4px; $labelStyle\">Drives: </span><span style=\"font-size: 150%; $valueStyle\">${numDrives}</span><br />\r\n    <span style=\"display: inline-block; margin: 0; width: 75px; text-align: right; padding-right: 4px; $labelStyle\">Docker Containers: </span><span style=\"font-size: 150%; $valueStyle\">${numDockerRunning}</span>/<span style=\"font-size: 100%; $valueStyle2\">${numDockerTotal}</span><br />\r\n\r\n</span>"
   },
   "targets": [
    {
     "query": "from(bucket: \"sys-metrics\")\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"mem\" and r[\"_field\"] == \"total\" and r.host == \"${host}\")\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n    _value: r._value, _time: r._time, _field: r._field\r\n  }))\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Host Process Info",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 11, "y": 2 },
   "targets": [
    {
     "query": "import \"experimental/query\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r[\"_measurement\"] == \"processes\" and\r\n      r.host == \"$host\"\r\n  )\r\n  |> query.filterFields(\r\n    fields: [\"total_threads\", \"total\", \"sleeping\", \"idle\", \"zombies\"]\r\n  )\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> last()\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"_time\", \"_start\", \"_stop\", \"_measurement\", \"host\"])\r\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "[$host] CPU Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host CPU Load History",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r[\"_measurement\"] == \"cpu\" and\r\n      r[\"_field\"] == \"usage_user\" and \r\n      r[\"cpu\"] !~ /^cpu-total/ and\r\n      r[\"host\"] =~ /^${host}$/\r\n  )\r\n|> map(fn: (r) => ({\r\n    _time: r._time, _field: int(v: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)) + 1, _value: r._value\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Host Core Loads",
     "type": "bargauge",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "query": "import \"strings\"\r\n\r\nfrom(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n      r[\"_measurement\"] == \"cpu\" and\r\n      r[\"_field\"] == \"usage_user\" and \r\n      r[\"cpu\"] !~ /^cpu-total/ and\r\n      r[\"host\"] =~ /^${host}$/\r\n  )\r\n  |> last()\r\n  |> map(fn: (r) => ({_value: r._value, _time: r._time, _field: int(v: strings.replace(v: r.cpu, t: \"cpu\", u: \"\", i: 1)) + 1 }))\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Host CPU package",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"cpu\" and\r\n    r[\"_field\"] == \"usage_idle\" and \r\n    r[\"cpu\"] == \"cpu-total\" and\r\n    r[\"host\"] =~ /^${host}$/\r\n  )\r\n  |> map(fn: (r) => ({ r with _value: float(v: r._value) * -1.0 + 100.0 }))\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"Total\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
      },
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"cpu\" and\r\n    r[\"_field\"] == \"usage_iowait\" and \r\n    r[\"cpu\"] == \"cpu-total\" and\r\n    r[\"host\"] =~ /^${host}$/\r\n  )\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"IO Wait\" }))\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"cpu\" and\r\n    r[\"_field\"] == \"usage_nice\" and \r\n    r[\"cpu\"] == \"cpu-total\" and\r\n    r[\"host\"] =~ /^${host}$/\r\n  )\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"Nice\" }))\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"cpu\" and\r\n    r[\"_field\"] == \"usage_user\" and \r\n    r[\"cpu\"] == \"cpu-total\" and\r\n    r[\"host\"] =~ /^${host}$/\r\n  )\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"User\" }))\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"cpu\" and\r\n    r[\"_field\"] == \"usage_softirq\" and \r\n    r[\"cpu\"] == \"cpu-total\" and\r\n    r[\"host\"] =~ /^${host}$/\r\n  )\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"Soft IRQ\" }))\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r[\"_measurement\"] == \"cpu\" and\r\n    r[\"_field\"] == \"usage_system\" and \r\n    r[\"cpu\"] == \"cpu-total\" and\r\n    r[\"host\"] =~ /^${host}$/\r\n  )\r\n  |> map(fn: (r) => ({ _value:r._value, _time:r._time, _field: \"System\" }))\r\n  |> aggregateWindow(every: $__interval, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Docker Containers CPU Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\r\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n|> filter(fn: (r) => \r\n    r._measurement == \"docker_container_cpu\" and\r\n    r._field == \"usage_percent\" and\r\n    r.host =~ /^$host$/\r\n)\r\n|> map(fn: (r) => ({ _value: r._value / float(v: ${cpucores}), _time: r._time, _field: r.container_name }))\r\n|> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\r\n|> yield(name: \"sum\")"
      }
     ]
    }
   ]
  },
  {
   "title": "[$host] Memory Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Host Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"mem\" and\r\n    r._field == \"used\" and\r\n    r.host =~ /^$host$/\r\n  )\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Used\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"mem\" and\r\n    r._field == \"buffered\" and\r\n    r.host =~ /^$host$/\r\n  )\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Buffered\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"mem\" and\r\n    r._field == \"cached\" and\r\n    r.host =~ /^$host$/\r\n  )\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Cached\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"mem\" and\r\n    r._field == \"free\" and\r\n    r.host =~ /^$host$/\r\n  )\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Free\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"mem\" and\r\n    r._field == \"total\" and\r\n    r.host =~ /^$host$/\r\n  )\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Total\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Container Memory Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => \r\n        r._measurement == \"docker_container_mem\" and\r\n        r._field == \"usage\" and\r\n        r.host =~ /^$host$/\r\n    )\r\n    |> map(fn: (r) => ({ _value: r._value / $cpucores, _time: r._time, _field: r.container_name }))\r\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n    |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "[$host] Network Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"net\" and\r\n    r._field == \"bytes_recv\" and\r\n    r.host =~ /^$host$/\r\n  )\r\n  |> derivative( unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\" )\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"In\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      },
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"net\" and\r\n    r._field == \"bytes_sent\" and\r\n    r.host =~ /^$host$/\r\n  )\r\n  |> derivative( unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\" )\r\n  |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: \"Out\" }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Container RX",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => \r\n    r._measurement == \"docker_container_net\" and\r\n    r._field == \"rx_bytes\" and\r\n    r.host =~ /^$host$/\r\n    )\r\n    |> derivative( unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\" )\r\n    |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: r.container_name }))\r\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n    |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Container TX",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => \r\n    r._measurement == \"docker_container_net\" and\r\n    r._field == \"tx_bytes\" and\r\n    r.host =~ /^$host$/\r\n    )\r\n    |> derivative( unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\" )\r\n    |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: r.container_name }))\r\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n    |> yield(name: \"last\")"
      }
     ]
    }
   ]
  },
  {
   "title": "[$host] Disks Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Consumption",
     "type": "table",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |>    filter(fn: (r) => r._measurement == \"disk\")\r\n  |>    filter(fn: (r) => r._field == \"free\" or r._field == \"used\" or r._field == \"total\")\r\n  |>    filter(fn: (r) => r.host =~ /^$host$/)\r\n  |>    filter(fn: (r) => r.path !~ /\\/var\\/lib\\/docker\\/btrfs.*/)\r\n  |>    filter(fn: (r) => r.device !~ /loop.*/)\r\n  |> last()\r\n  |> map(fn: (r) => ({\r\n      r with\r\n      _value: if r._field == \"free\" then float(v: r._value) / 1000000000.0 else float(v: r._value),\r\n      _value: if r._field == \"free\" then float(v: r._value) / 1000000000.0 else float(v: r._value),\r\n    }))\r\n  |> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\r\n  |> drop(columns: [\"path\", \"fstype\", \"_measurement\", \"host\", \"mode\", \"used_percent\", \"_time\", \"_start\", \"_stop\"])\r\n  |> group()\r\n  |> yield(name: \"last\")"
      }
     ]
    },
    {
     "title": "Data Growth Today",
     "type": "stat",
     "description": "The panel shows the growth of the fuse filesystem including any cache drives. ",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "alias": "Space Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "disk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"disk\" and\r\n    r._field == \"used\" and\r\n    r.host =~ /^$host$/ \r\n  )\r\n  |> map(fn: (r) => ({\r\n    _time: r._time, _field: r.device, _value: r._value\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "device", "operator": "=", "value": "shfs" }
       ]
      }
     ]
    },
    {
     "title": "Data Growth This Month",
     "type": "stat",
     "description": "The panel shows the growth of the fuse filesystem including any cache drives. ",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "alias": "Space Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "disk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"disk\" and\r\n    r._field == \"used\" and\r\n    r.host =~ /^$host$/ \r\n  )\r\n  |> map(fn: (r) => ({\r\n    _time: r._time, _field: r.device, _value: r._value\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "device", "operator": "=", "value": "shfs" }
       ]
      }
     ]
    },
    {
     "title": "Data Growth This Week",
     "type": "stat",
     "description": "The panel shows the growth of the fuse filesystem including any cache drives. ",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "alias": "Space Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "disk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"disk\" and\r\n    r._field == \"used\" and\r\n    r.host =~ /^$host$/ \r\n  )\r\n  |> map(fn: (r) => ({\r\n    _time: r._time, _field: r.device, _value: r._value\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "device", "operator": "=", "value": "shfs" }
       ]
      }
     ]
    },
    {
     "title": "Data Growth This Year",
     "type": "stat",
     "description": "The panel shows the growth of the fuse filesystem including any cache drives. ",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "diff" ] } },
     "targets": [
      {
       "alias": "Space Used",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" }
       ],
       "measurement": "disk",
       "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => \r\n    r._measurement == \"disk\" and\r\n    r._field == \"used\" and\r\n    r.host =~ /^$host$/\r\n  )\r\n  |> map(fn: (r) => ({\r\n    _time: r._time, _field: r.device, _value: r._value\r\n  }))\r\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\r\n  |> yield(name: \"last\")",
       "select": [
        [
         { "params": [ "used" ], "type": "field" },
         {
          "params": [],
          "type": "last"
         }
        ]
       ],
       "tags": [
        { "key": "host", "operator": "=~", "value": "/^$host$/" },
        { "condition": "AND", "key": "device", "operator": "=", "value": "shfs" }
       ]
      }
     ]
    },
    {
     "title": "All Disk Write",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => \r\n    r._measurement == \"diskio\" and\r\n    r._field == \"write_bytes\" and\r\n    r.host =~ /^$host$/ and\r\n    r.name !~ /^sd.*1|md|loop|nvme0n\\dp.*/\r\n    )\r\n    |> derivative( unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\" )\r\n    |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: r.name }))\r\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
      }
     ]
    },
    {
     "title": "All Disk Read",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "query": "from(bucket: v.defaultBucket)\r\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n    |> filter(fn: (r) => \r\n    r._measurement == \"diskio\" and\r\n    r._field == \"read_bytes\" and\r\n    r.host =~ /^$host$/ and\r\n    r.name !~ /^sd.*1|md|loop|nvme0n\\dp.*/\r\n    )\r\n    |> derivative( unit: 1s, nonNegative: true, columns: [\"_value\"], timeColumn: \"_time\" )\r\n    |> map(fn: (r) => ({ _value: r._value, _time: r._time, _field: r.name }))\r\n    |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 4, "w": 12, "x": 12, "y": 48 } }
   ]
  }
 ]
}